src/main/java/au/com/lasercommando/model/map/AuthorEnum.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.map;

/**
 *
 * @author Kobus
 */
public enum AuthorEnum {
    LASER_COMMANDO(1, "Laser Commando Maps"),
    CUSTOM(2, "Custom Map");
    
    private int code;
    private String description;

    private AuthorEnum(int code, String description) {
        this.code = code;
        this.description = description;
    }    

    public static AuthorEnum findEnum(String roleDescription) {
        for (AuthorEnum enumValue : values()) {
            if (enumValue.getDescription().equals(roleDescription)) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for description " + roleDescription);
    }

    public static AuthorEnum findEnum(int code) {
        for (AuthorEnum enumValue : values()) {
            if (enumValue.getCode() == code) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for code " + code);
    }
    
    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
        
}

src/main/java/au/com/lasercommando/model/map/Map.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.map;

import au.com.lasercommando.model.event.Contact;
import java.util.List;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 *
 * @author Kobus
 */
@Document
public class Map implements java.io.Serializable  {
    @Id
    private String id;
    private String name;
    private String description;
    private int mapCategory;
    private int mapDifficulty;
    private String address1;
    private String address2;
    private String city;
    private String state;
    private String postalCode;
    private String coords;
    private String website;
    private int zoom;    
    private List<Contact> contactList;
    private double pricePerPlayer;

    public double getPricePerPlayer() {
        return pricePerPlayer;
    }

    public void setPricePerPlayer(double pricePerPlayer) {
        this.pricePerPlayer = pricePerPlayer;
    }

    public List<Contact> getContactList() {
        return contactList;
    }

    public void setContactList(List<Contact> contactList) {
        this.contactList = contactList;
    }

    public String getLocation() {
        StringBuilder location = new StringBuilder();
        location.append(address1).append(", ");
        location.append(address2).append(", ");
        location.append(city).append(", ");
        location.append(state).append(", ");
        location.append(postalCode);
        
        return location.toString();
    }
    
    public int getZoom() {
        return zoom;
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }
    
    public String getCoords() {
        return coords;
    }

    public void setCoords(String coords) {
        this.coords = coords;
    }
    
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
    
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getMapCategory() {
        return mapCategory;
    }

    public void setMapCategory(int mapCategory) {
        this.mapCategory = mapCategory;
    }

    public String getMapCategoryDescription() {
        return MapCategoryEnum.findEnum(mapCategory).getDescription();
    }
    
    public int getMapDifficulty() {
        return mapDifficulty;
    }

    public void setMapDifficulty(int mapDifficulty) {
        this.mapDifficulty = mapDifficulty;
    }

    public String getMapDifficultyDescription() {
        return MapDifficultyEnum.findEnum(mapDifficulty).getDescription();
    }
    
    public Map() {
        id = java.util.UUID.randomUUID().toString();
        zoom = 18;
        state = "QLD";
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Map other = (Map) obj;
        if ((this.id == null) ? (other.id != null) : !this.id.equals(other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }     
}

src/main/java/au/com/lasercommando/model/map/MapCategoryEnum.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.map;

/**
 *
 * @author Kobus
 */
public enum MapCategoryEnum {
    UNSPECIFIED(0, "Unspecified"),
    WOODLANDS(1, "Woodlands"),
    INFLATABLES(2, "Inflatables"),
    URBAN(3, "Urban");
    
    private int code;
    private String description;

    private MapCategoryEnum(int code, String description) {
        this.code = code;
        this.description = description;
    }    

    public static MapCategoryEnum findEnum(String roleDescription) {
        for (MapCategoryEnum enumValue : values()) {
            if (enumValue.getDescription().equals(roleDescription)) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for description " + roleDescription);
    }

    public static MapCategoryEnum findEnum(int code) {
        for (MapCategoryEnum enumValue : values()) {
            if (enumValue.getCode() == code) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for code " + code);
    }
    
    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
        
}

src/main/java/au/com/lasercommando/model/map/MapDifficultyEnum.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.map;

/**
 *
 * @author Kobus
 */
public enum MapDifficultyEnum {
    LEVEL_ONE(1, "Indoor laser games"), //school hall
    LEVEL_TWO(2, "School oval"), //school oval, music
    LEVEL_THREE(3, "Woodlands camp site with slight growth"), //scouts camp 2
    LEVEL_FOUR(4, "Woodlands camp site with lots of growth"), //scouts camp 9
    LEVEL_FIVE(5, "Woodlands camp site night game"); //scouts night
    
    private int code;
    private String description;

    private MapDifficultyEnum(int code, String description) {
        this.code = code;
        this.description = description;
    }

        
    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public static MapDifficultyEnum findEnum(int code) {
        for (MapDifficultyEnum enumValue : values()) {
            if (enumValue.getCode() == code) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for code " + code);
    }

}

src/main/java/au/com/lasercommando/web/bean/ManageMapBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.web.bean;

import au.com.lasercommando.model.map.Map;
import au.com.lasercommando.model.map.MapCategoryEnum;
import au.com.lasercommando.service.MapService;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author KobusVM
 */
@Controller
@Scope("session")
public class ManageMapBean implements java.io.Serializable {
    @Resource
    private MapService mapService;
    private Map selectedMap;
    private boolean editMap;

    public MapCategoryEnum[] getMapCategoryList() {
        return MapCategoryEnum.values();
    }

    public boolean isEditMap() {
        return editMap;
    }

    public void setEditMap(boolean editMap) {
        this.editMap = editMap;
    }

    public Map getSelectedMap() {
        return selectedMap;
    }

    public void setSelectedMap(Map selectedMap) {
        this.selectedMap = selectedMap;
    }
    
    public List<Map> getAllMaps() {
        return mapService.findAll();
    }

    @PostConstruct
    public void init() {
        editMap = false;
        selectedMap = new Map();
    }

    public String edit(Map map) {
        this.selectedMap = map;
        editMap = true;
        
        return "managemap.jsf?faces-redirect=true";
    }

    public String update() {
        mapService.save(selectedMap);
        editMap = false;
        return "maplist.jsf?faces-redirect=true";
    }

    public String add() {
        mapService.save(selectedMap);
        return "maplist.jsf?faces-redirect=true";
    }

}

src/main/webapp/admin/map/managemap.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/sixBoxLayout.xhtml">

    <ui:define name="center">
        <h:form id="addMapForm">
            <h:panelGrid columns="1">
                <h:panelGroup>
                    <h:outputText value="All fields are mandatory "/>
                </h:panelGroup>
            </h:panelGrid>

            <h:panelGrid columns="4">
                <h:outputText value="Location Name"/>
                <h:panelGroup>
                    <h:inputText id="mapName" value="#{manageMapBean.selectedMap.name}"
                                 maxlength="30"/>
                </h:panelGroup>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Category"/>
                <p:selectOneMenu value="#{manageMapBean.selectedMap.mapCategory}">
                    <f:selectItems value="#{manageMapBean.mapCategoryList}" var="mapCategoryLocal"
                                   itemValue="#{mapCategoryLocal.code}" itemLabel="#{mapCategoryLocal.description}" />
                </p:selectOneMenu>

                <h:outputText value="Difficulty"/>
                <p:rating value="#{manageMapBean.selectedMap.mapDifficulty}"/>

                <h:panelGroup>
                    <h:outputText value="Address line 1"/>
                    <h:outputText styleClass="required-field" value=" *" />
                </h:panelGroup>
                <h:inputText id="addressLine1" value="#{manageMapBean.selectedMap.address1}" required="true"
                             style="#{component.valid ? '' : 'border: solid 1px red;'}"
                             requiredMessage="Please enter address line 1" maxlength="20"/>

                <h:panelGroup>
                    <h:outputText value="Address line 2"/>
                    <h:outputText styleClass="required-field" value=" *" />
                </h:panelGroup>
                <h:inputText id="addressLine2" value="#{manageMapBean.selectedMap.address2}" required="true"
                             style="#{component.valid ? '' : 'border: solid 1px red;'}"
                             requiredMessage="Please enter address line 2" maxlength="20"/>

                <h:panelGroup>
                    <h:outputText value="City/Town"/>
                    <h:outputText styleClass="required-field" value=" *" />
                </h:panelGroup>
                <h:inputText id="city" value="#{manageMapBean.selectedMap.city}" required="true"
                             style="#{component.valid ? '' : 'border: solid 1px red;'}"
                             requiredMessage="Please enter the city" maxlength="20"/>

                <h:panelGroup>
                    <h:outputText value="State"/>
                    <h:outputText styleClass="required-field" value=" *" />
                </h:panelGroup>
                <h:inputText id="state" value="#{manageMapBean.selectedMap.state}" required="true"
                             style="#{component.valid ? '' : 'border: solid 1px red;'}"
                             requiredMessage="Please enter the state"/>

                <h:panelGroup>
                    <h:outputText value="Postal code"/>
                    <h:outputText styleClass="required-field" value=" *" />
                </h:panelGroup>
                <h:inputText id="postalCode" value="#{manageMapBean.selectedMap.postalCode}" required="true"
                             style="#{component.valid ? '' : 'border: solid 1px red;'}"
                             requiredMessage="Please enter the postal code" maxlength="6"/>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Location Notes/Directions"/>
                <h:panelGroup>
                    <h:inputTextarea id="mapDescription" cols="40" rows="5" value="#{manageMapBean.selectedMap.description}" >
                        <f:validateLength maximum="255"/>
                    </h:inputTextarea>
                </h:panelGroup>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Website"/>
                <h:inputText value="#{manageMapBean.selectedMap.website}" style="width: 200px"/>

                <h:outputText value="Coordinates"/>
                <h:inputText value="#{manageMapBean.selectedMap.coords}"/>

                <h:outputText value="Zoom level"/>
                <h:inputText value="#{manageMapBean.selectedMap.zoom}"/>

                <h:outputText value="Price per player"/>
                <h:inputText value="#{manageMapBean.selectedMap.pricePerPlayer}"/>

            </h:panelGrid>
            
            <p:commandButton value="Back" action="maplist.jsf?faces-redirect=true" immediate="true" rendered="#{manageMapBean.editMap}"/>
            <p:commandButton value="Update" action="#{manageMapBean.update}" rendered="#{manageMapBean.editMap}"/>

            <p:commandButton value="Back" action="../index.jsf?faces-redirect=true" immediate="true"  rendered="#{!manageMapBean.editMap}"/>
            <p:commandButton value="Add" action="#{manageMapBean.add}" rendered="#{!manageMapBean.editMap}"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/map/maplist.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/sixBoxLayout.xhtml">

    <ui:define name="center">
        <h:form>
            <p:dataTable value="#{manageMapBean.allMaps}" var="map" rows="8"
                         styleClass="create-game-data-table" paginator="true" paginatorPosition="bottom">
                <p:column headerText="Name" filterBy="#{map.name}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{map.name}"/>
                </p:column>
                <p:column headerText="Category" filterBy="#{map.mapCategoryDescription}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{map.mapCategoryDescription}"/>
                </p:column>
                <p:column headerText="Difficulty" filterBy="#{map.mapDifficulty}" filterMatchMode="contains"
                          filterStyle="width: 40px" style="width: 90px">
                    <p:rating value="#{map.mapDifficulty}" readonly="true"/>
                </p:column>
                <p:column headerText="Address">
                    <h:outputText value="#{map.address1}, #{map.address2}, #{map.city}, #{map.state}, #{map.postalCode}"/>
                </p:column>
                <p:column headerText="Coords">
                    <h:outputText value="#{map.coords}"/>
                </p:column>
                <p:column headerText="Zoom">
                    <h:outputText value="#{map.zoom}"/>
                </p:column>
                <p:column headerText="Per player">
                    <h:outputText value="#{map.pricePerPlayer}"/>
                </p:column>
                <p:column>
                    <p:commandButton value="EDIT"
                                    action="#{manageMapBean.edit(map)}"
                                    immediate="true"/>
                </p:column>
            </p:dataTable>
            <p:commandButton value="Back" action="../index.jsf?faces-redirect=true" immediate="true"/>
        </h:form>
    </ui:define>
</ui:composition>