src/main/java/au/com/lasercommando/model/event/Contact.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

/**
 *
 * @author KobusVM
 */
public class Contact implements java.io.Serializable {
    private String id;
    private String firstname;
    private String surname;
    private String telephoneNumber;
    private String email;
    private String groupName;
    private int averageAgeGroup;
    private boolean eventCreator;
    private String howDidYouFindUs;

    public String getHowDidYouFindUs() {
        return howDidYouFindUs;
    }

    public void setHowDidYouFindUs(String howDidYouFindUs) {
        this.howDidYouFindUs = howDidYouFindUs;
    }

    public int getAverageAgeGroup() {
        return averageAgeGroup;
    }

    public void setAverageAgeGroup(int averageAgeGroup) {
        this.averageAgeGroup = averageAgeGroup;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public boolean isEventCreator() {
        return eventCreator;
    }

    public void setEventCreator(boolean eventCreator) {
        this.eventCreator = eventCreator;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    public String getAverageAgeGroupDescription() {
        return ContactHelper.convertAverageAgeGroup(averageAgeGroup);
    }
    
    public Contact() {
        id = java.util.UUID.randomUUID().toString();
    }
}

src/main/java/au/com/lasercommando/model/event/Event.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

import au.com.lasercommando.model.player.Player;
import au.com.lasercommando.Constants;
import au.com.lasercommando.model.map.Map;
import au.com.lasercommando.model.map.AuthorEnum;
import au.com.lasercommando.model.map.MapCategoryEnum;
import au.com.lasercommando.model.map.MapDifficultyEnum;
import au.com.lasercommando.util.ShortIdGenerator;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 *
 * @author KobusVM
 */
@Document
public class Event implements java.io.Serializable {
    @Id
    private String id;
    private String name;
    private Date date;
    private boolean privateEvent;
    private String mapId;
    private String contactId;
    private Map map;
    private int session;
    private int status;
    private int playersJoined;
    private int maxPlayerCount;
    private String password;
    private List<Player> playerList;
    private List<Payment> paymentList;    
    private int author;
    private double pricePerPlayer;
    private String alternateId;
    private boolean active;

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }        

    public String getAlternateId() {
        return alternateId;
    }

    public void setAlternateId(String alternateId) {
        this.alternateId = alternateId;
    }

    public double getPricePerPlayer() {
        return pricePerPlayer;
    }

    public void setPricePerPlayer(double pricePerPlayer) {
        this.pricePerPlayer = pricePerPlayer;
    }

    public int getAuthor() {
        return author;
    }

    public void setAuthor(int author) {
        this.author = author;
    }

    public String getContactId() {
        return contactId;
    }

    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    public String getMapId() {
        return mapId;
    }

    public void setMapId(String mapId) {
        this.mapId = mapId;
    }
    
    public boolean isPrivateEvent() {
        return privateEvent;
    }

    public void setPrivateEvent(boolean privateEvent) {
        this.privateEvent = privateEvent;
    }

    public boolean getPrivateEvent() {
        return privateEvent;
    }

    public void addPayment(Payment payment) {
        paymentList.add(payment);
    }

    public List<Payment> getPaymentList() {
        return paymentList;
    }

    public void setPaymentList(List<Payment> paymentList) {
        this.paymentList = paymentList;
    }

    public void addPlayer(Player player) {
        playerList.add(player);
    }

    public Collection<Player> getPlayerList() {
        return playerList;
    }

    public void setPlayerList(List<Player> playerList) {
        this.playerList = playerList;
    }

    public int getMaxPlayerCount() {
        return maxPlayerCount;
    }

    public void setMaxPlayerCount(int maxPlayerCount) {
        this.maxPlayerCount = maxPlayerCount;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getPlayersJoined() {
        return playersJoined;
    }

    public void setPlayersJoined(int playersJoined) {
        this.playersJoined = playersJoined;
    }        

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getSession() {
        return session;
    }

    public String getSessionDescription() {
        return SessionHelper.convertSession(session);
    }

    public void setSession(int session) {
        this.session = session;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getDateFormatted() {
        SimpleDateFormat dateFormat = new SimpleDateFormat(Constants.DATE_FORMAT);
        return dateFormat.format(date);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Map getMap() {
        return map;
    }

    public void setMap(Map map) {
        this.map = map;
    }
    
    public Event() {
        id = java.util.UUID.randomUUID().toString();
        playerList = new ArrayList<Player>();
        paymentList = new ArrayList<Payment>();
        alternateId = ShortIdGenerator.generate();
        active = true;
        
        privateEvent = true;
        status = EventStatusEnum.AVAILABLE.getCode();
        maxPlayerCount = 40;
        playersJoined = 10;
        author = AuthorEnum.CUSTOM.getCode();
        
        map = new Map();
        map.setMapCategory(MapCategoryEnum.INFLATABLES.getCode());
        map.setMapDifficulty(MapDifficultyEnum.LEVEL_TWO.getCode());
    }
}

src/main/webapp/bookgame/payPalBookPage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:map="http://java.sun.com/jsf/composite/components/map"
                xmlns:booking="http://java.sun.com/jsf/composite/components/booking"
                template="/templates/sixBoxLayout.xhtml">
    
    <ui:define name="center">
        <h:panelGrid columns="1" class="create-game-data-table">
            <h:panelGroup styleClass="white-anchor">
                <h:outputText value="Thank you for booking a game with Laser Commando.  "/>
                <h:outputText value="Please check your e-mail for a booking confirmation, invitation letter and a "/>
                <a href="/forms/LaserCommandoMembershipForm.pdf">membership form</a>
            </h:panelGroup>
            <h:outputText value="Event summary"/>
            <h:panelGrid columns="4" class="create-game-data-table">

                <h:outputText styleClass="book-heading" value="Game"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Game name"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.name}"/>

                <h:outputText value="Private game"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.privateEvent}"/>

                <h:outputText value="Date"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.date}">
                    <f:convertDateTime pattern="#{webConstantsBean.dateFormat}"/>
                </h:outputText>

                <h:outputText value="Time"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.sessionDescription}"/>

                <h:outputText value="Players paid for"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.paidForPlayers}"/>

                <h:outputText value="Total cost"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.totalCost}">
                    <f:convertNumber type="currency" />
                </h:outputText>
                
                <h:outputText value="Discount received"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.discountAmount}">
                    <f:convertNumber type="currency" />
                </h:outputText>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText styleClass="book-heading" value="Contact"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Group name"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.groupName}"/>

                <h:outputText value="Average age of the group"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.averageAgeGroupDescription}"/>

                <h:outputText value="Firstname"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.firstname}"/>

                <h:outputText value="Surname"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.surname}"/>

                <h:outputText value="Telephone number"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.telephoneNumber}"/>

                <h:outputText value="E-mail"/>
                <h:outputText value="#{eventSelectionBean.selectedPayment.contact.email}"/>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText styleClass="book-heading" value="Location"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Location name"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.name}"/>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

                <h:outputText value="Address 1"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.address1}"/>

                <h:outputText value="Address 2"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.address2}"/>

                <h:outputText value="City/Town"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.city}"/>

                <h:outputText value="State"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.state}"/>

                <h:outputText value="Postal code"/>
                <h:outputText value="#{eventSelectionBean.selectedEvent.event.map.postalCode}"/>

                <h:outputText value="&#160;"/>
                <h:outputText value="&#160;"/>

            </h:panelGrid>
        </h:panelGrid>


        <!-- Google Code for Booked Conversion Page -->
        <script type="text/javascript">
            /* <![CDATA[ */
            var google_conversion_id = 1016045146;
            var google_conversion_language = "en";
            var google_conversion_format = "3";
            var google_conversion_color = "ffffff";
            var google_conversion_label = "KtyWCP69vQMQ2ry-5AM";
            var google_conversion_value = 500;
            /* ]]> */
        </script>
        <script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
        </script>
        <noscript>
            <div style="display:inline;">
                <img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/1016045146/?value=0&amp;label=KtyWCP69vQMQ2ry-5AM&amp;guid=ON&amp;script=0"/>
            </div>
        </noscript>
        
    </ui:define>

</ui:composition>

src/main/webapp/bookgame/payPalErrorPage.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:map="http://java.sun.com/jsf/composite/components/map"
                xmlns:booking="http://java.sun.com/jsf/composite/components/booking"
                template="/templates/sixBoxLayout.xhtml">
    
    <ui:define name="center">
        <h:panelGrid columns="1" class="eighty-percent-table">
            <h:outputText value="Thank you for booking an event with Laser Commando"/>
            <h:outputText value="It seems an error occured returning from PayPal.  Please contact Laser Commando to book an event"/>
        </h:panelGrid>
        
    </ui:define>

</ui:composition>