src/main/java/au/com/lasercommando/model/event/AverageAgeEnum.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

/**
 *
 * @author Kobus
 */
public enum AverageAgeEnum {
    GROUP1(1, "5 to 8 years", 5),
    GROUP2(2, "8 to 10 years", 8),
    GROUP3(3, "10 to 12 years", 10),
    GROUP4(4, "12 to 14 years", 12),
    GROUP5(5, "14 to 16 years", 14),
    GROUP6(6, "16 to 18 years", 16),
    GROUP7(7, "18+", 18);
    
    private int code;
    private String description;
    private int startAge;

    private AverageAgeEnum(int code, String description, int startAge) {
        this.code = code;
        this.description = description;
        this.startAge = startAge;
    }    

    public static AverageAgeEnum findEnum(String description) {
        for (AverageAgeEnum enumValue : values()) {
            if (enumValue.getDescription().equals(description)) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for description " + description);
    }

    public static AverageAgeEnum findEnum(int code) {
        for (AverageAgeEnum enumValue : values()) {
            if (enumValue.getCode() == code) {
                return enumValue;
            }
        }

        throw new RuntimeException("Enum not found for code " + code);
    }

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getStartAge() {
        return startAge;
    }

    public void setStartAge(int startAge) {
        this.startAge = startAge;
    }
}

src/main/java/au/com/lasercommando/model/event/CheckOutResponse.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

import com.paypal.sdk.core.nvp.NVPDecoder;

/**
 *
 * @author KobusVM
 */
public class CheckOutResponse {
    private NVPDecoder response;
    
    public CheckOutResponse(NVPDecoder response) {
        this.response = response;
    }
    
    public String getTotalAmount() {
        return response.get("PAYMENTREQUEST_0_AMT");
    }
    
    public String getToken() {
        return response.get("TOKEN");
    }
}

src/main/java/au/com/lasercommando/model/event/Contact.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

/**
 *
 * @author KobusVM
 */
public class Contact implements java.io.Serializable {
    private String id;
    private String firstname;
    private String surname;
    private String telephoneNumber;
    private String email;
    private String groupName;
    private int averageAgeGroup;
    private boolean eventCreator;
    private String howDidYouFindUs;

    public String getHowDidYouFindUs() {
        return howDidYouFindUs;
    }

    public void setHowDidYouFindUs(String howDidYouFindUs) {
        this.howDidYouFindUs = howDidYouFindUs;
    }

    public int getAverageAgeGroup() {
        return averageAgeGroup;
    }

    public void setAverageAgeGroup(int averageAgeGroup) {
        this.averageAgeGroup = averageAgeGroup;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public boolean isEventCreator() {
        return eventCreator;
    }

    public void setEventCreator(boolean eventCreator) {
        this.eventCreator = eventCreator;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    public String getAverageAgeGroupDescription() {
        return ContactHelper.convertAverageAgeGroup(averageAgeGroup);
    }
    
    public Contact() {
        id = java.util.UUID.randomUUID().toString();
    }
}

src/main/java/au/com/lasercommando/model/event/Event.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

import au.com.lasercommando.model.player.Player;
import au.com.lasercommando.Constants;
import au.com.lasercommando.model.map.Map;
import au.com.lasercommando.model.map.AuthorEnum;
import au.com.lasercommando.model.map.MapCategoryEnum;
import au.com.lasercommando.model.map.MapDifficultyEnum;
import au.com.lasercommando.util.ShortIdGenerator;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 *
 * @author KobusVM
 */
@Document
public class Event implements java.io.Serializable {
    @Id
    private String id;
    private String name;
    private Date date;
    private boolean privateEvent;
    private String mapId;
    private String contactId;
    private Map map;
    private int session;
    private int status;
    private int playersJoined;
    private int maxPlayerCount;
    private String password;
    private List<Player> playerList;
    private List<Payment> paymentList;    
    private int author;
    private double pricePerPlayer;
    private String alternateId;
    private boolean active;

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }        

    public String getAlternateId() {
        return alternateId;
    }

    public void setAlternateId(String alternateId) {
        this.alternateId = alternateId;
    }

    public double getPricePerPlayer() {
        return pricePerPlayer;
    }

    public void setPricePerPlayer(double pricePerPlayer) {
        this.pricePerPlayer = pricePerPlayer;
    }

    public int getAuthor() {
        return author;
    }

    public void setAuthor(int author) {
        this.author = author;
    }

    public String getContactId() {
        return contactId;
    }

    public void setContactId(String contactId) {
        this.contactId = contactId;
    }

    public String getMapId() {
        return mapId;
    }

    public void setMapId(String mapId) {
        this.mapId = mapId;
    }
    
    public boolean isPrivateEvent() {
        return privateEvent;
    }

    public void setPrivateEvent(boolean privateEvent) {
        this.privateEvent = privateEvent;
    }

    public boolean getPrivateEvent() {
        return privateEvent;
    }

    public void addPayment(Payment payment) {
        paymentList.add(payment);
    }

    public List<Payment> getPaymentList() {
        return paymentList;
    }

    public void setPaymentList(List<Payment> paymentList) {
        this.paymentList = paymentList;
    }

    public void addPlayer(Player player) {
        playerList.add(player);
    }

    public Collection<Player> getPlayerList() {
        return playerList;
    }

    public void setPlayerList(List<Player> playerList) {
        this.playerList = playerList;
    }

    public int getMaxPlayerCount() {
        return maxPlayerCount;
    }

    public void setMaxPlayerCount(int maxPlayerCount) {
        this.maxPlayerCount = maxPlayerCount;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getPlayersJoined() {
        return playersJoined;
    }

    public void setPlayersJoined(int playersJoined) {
        this.playersJoined = playersJoined;
    }        

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getSession() {
        return session;
    }

    public String getSessionDescription() {
        return SessionHelper.convertSession(session);
    }

    public void setSession(int session) {
        this.session = session;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getDateFormatted() {
        SimpleDateFormat dateFormat = new SimpleDateFormat(Constants.DATE_FORMAT);
        return dateFormat.format(date);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Map getMap() {
        return map;
    }

    public void setMap(Map map) {
        this.map = map;
    }
    
    public Event() {
        id = java.util.UUID.randomUUID().toString();
        playerList = new ArrayList<Player>();
        paymentList = new ArrayList<Payment>();
        alternateId = ShortIdGenerator.generate();
        active = true;
        
        privateEvent = true;
        status = EventStatusEnum.AVAILABLE.getCode();
        maxPlayerCount = 40;
        playersJoined = 10;
        author = AuthorEnum.CUSTOM.getCode();
        
        map = new Map();
        map.setMapCategory(MapCategoryEnum.INFLATABLES.getCode());
        map.setMapDifficulty(MapDifficultyEnum.LEVEL_TWO.getCode());
    }
}

src/main/java/au/com/lasercommando/model/event/SessionHelper.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.model.event;

import java.util.HashMap;

/**
 *
 * @author dutoitk
 */
public class SessionHelper {
    private static final HashMap<Integer, String> hashMap = new HashMap<Integer, String>();
    static {
        hashMap.put(SessionEnum.SESSION1.getCode(), SessionEnum.SESSION1.getDescription());
        hashMap.put(SessionEnum.SESSION2.getCode(), SessionEnum.SESSION2.getDescription());
        hashMap.put(SessionEnum.SESSION3.getCode(), SessionEnum.SESSION3.getDescription());
        hashMap.put(SessionEnum.SESSION4.getCode(), SessionEnum.SESSION4.getDescription());
    }

    public static String convertSession(int session) {
        return hashMap.get(session);
    }
}

src/main/java/au/com/lasercommando/web/bean/ManageEventBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package au.com.lasercommando.web.bean;

import au.com.lasercommando.Constants;
import au.com.lasercommando.model.event.*;
import au.com.lasercommando.model.map.AuthorEnum;
import au.com.lasercommando.model.map.Map;
import au.com.lasercommando.model.product.PayPalProduct;
import au.com.lasercommando.model.product.Product;
import au.com.lasercommando.service.EventService;
import au.com.lasercommando.service.MapService;
import au.com.lasercommando.service.PayPalProductService;
import au.com.lasercommando.service.PlayerService;
import au.com.lasercommando.service.ProductService;
import java.util.List;
import java.util.Locale;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.MessageSource;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author KobusVM
 */
@Controller
@Scope("session")
public class ManageEventBean implements java.io.Serializable {

    @Resource
    private EventService eventService;
    @Resource
    private MapService mapService;
    @Resource
    private MessageSource messageSource;
    @Value("${price.per.player}")
    private double pricePerPlayer;
    private List<Map> mapList;
    private List<EventProxy> eventList;
    private EventProxy selectedEvent;
    private boolean editEvent;
    @Resource
    private PayPalProductService payPalProductService;
    @Resource
    private ProductService productService;

    public boolean isEditEvent() {
        return editEvent;
    }

    public void setEditEvent(boolean editEvent) {
        this.editEvent = editEvent;
    }

    public List<Map> getMapList() {
        return mapList;
    }

    public void setMapList(List<Map> mapList) {
        this.mapList = mapList;
    }

    public AuthorEnum[] getAuthorList() {
        return AuthorEnum.values();
    }

    public EventStatusEnum[] getEventStatusList() {
        return EventStatusEnum.values();
    }

    public SessionEnum[] getSessionList() {
        return SessionEnum.values();
    }

    public EventProxy getSelectedEvent() {
        return selectedEvent;
    }

    public void setSelectedEvent(EventProxy selectedEvent) {
        this.selectedEvent = selectedEvent;
    }

    public List<EventProxy> getAllEvents() {
        return eventList;
    }

    @PostConstruct
    public void init() {
        editEvent = false;
        selectedEvent = new EventProxy(new Event());
    }

    public String loadAlternateEventIdList() {
        eventList = eventService.findActiveEvents();
        return "event/eventlistDisplayAlternateId.jsf?faces-redirect=true";
    }

    public String loadEditEventList() {
        eventList = eventService.findActiveEvents();
        return "event/eventlist.jsf?faces-redirect=true";
    }

    public String newEvent() {
        initEvent();
        return "event/manageevent.jsf?faces-redirect=true";
    }

    private void initEvent() {
        this.selectedEvent = new EventProxy(new Event());
        selectedEvent.getEvent().setPlayersJoined(0);
        selectedEvent.getEvent().setMaxPlayerCount(Constants.MAX_PLAYERS);
        selectedEvent.getEvent().setStatus(EventStatusEnum.BOOKED.getCode());
        selectedEvent.getEvent().setPrivateEvent(false);
        selectedEvent.getEvent().setAuthor(AuthorEnum.LASER_COMMANDO.getCode());
        selectedEvent.getEvent().setPricePerPlayer(pricePerPlayer);
        mapList = mapService.findAll();
    }

    public String displayAlternateId(EventProxy eventProxy) {
        this.selectedEvent = eventProxy;
        return "eventAlternateId.jsf?faces-redirect=true";
    }

    public String edit(EventProxy eventProxy) {
        this.selectedEvent = eventProxy;
        editEvent = true;
        mapList = mapService.findAll();

        return "manageevent.jsf?faces-redirect=true";
    }

    public String update() {
        eventService.save(selectedEvent.getEvent());
        editEvent = false;
        return "eventlist.jsf?faces-redirect=true";
    }

    public void add() {
        eventService.save(selectedEvent.getEvent());
        initEvent();
        String newEvent = messageSource.getMessage("new.event.created", new Object[]{}, Locale.US);
        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, newEvent, newEvent);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public void specialChangeEventPricing() {
        List<EventProxy> eventList = eventService.findAll();
        for (EventProxy eventProxy : eventList) {
            Event event = eventProxy.getEvent();
            event.setPricePerPlayer(25);
            eventService.save(event);
        }
    }

    public void specialPopulateProducts() {
        List<PayPalProduct> list = payPalProductService.findAllActive();
        for (PayPalProduct payPalProduct : list) {
            Product product = payPalProduct.getProduct();
            product.setId(java.util.UUID.randomUUID().toString());
            product.setSortOrder(payPalProduct.getSortOrder());
            productService.save(product);
        }
    }

    public void specialChangeMapName() {
        List<EventProxy> eventProxyList = eventService.findAll();
        for (EventProxy eventProxy : eventProxyList) {
            Event event = eventProxy.getEvent();
            Map map = event.getMap();
            if ((map != null) && (map.getName() != null)) {
                if (map.getName().equals("Zillmere State School Oval")) {
                    map.setDescription("Zillmere State School Oval has some trees on the one side.  We will try to place the inflatables in a way that the trees also become part of the game.  That should help with getting some shade.  BBQ's are allowed.  There isn't any electricity, but we do have generators that can be hired.  We have access to the toilets of the school.  There is ample area for parking in Merritt Avenue adjacent to the oval.");
                    eventService.save(event);
                } else if (map.getName().equals("Murrenbong Scouts Camp 2")) {
                    map.setDescription("Murrongong Scouts Camp 2 has a porter potty, we can order a second one if needed.  There is a covered area about the size of a single garage.  The scouts do allow BBQ's, please contact them to make sure if they will allow your type of BBQ.  There isn't any electricity, but we do have generators that can be hired.");
                    eventService.save(event);
                }
            }
        }
    }

}

src/main/webapp/admin/event/eventAlternateId.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/sixBoxLayout.xhtml">

    <ui:define name="center">
        <h:form id="addEventForm">
            <h:panelGrid columns="1">
                <h:outputText value="GAME CODE" styleClass="text-box-30"/>
                <h:outputText value="#{manageEventBean.selectedEvent.event.alternateId}" styleClass="alternate-id-code"/>

            </h:panelGrid>

            <p:commandButton value="Back" action="eventlistDisplayAlternateId.jsf?faces-redirect=true" immediate="true"/>

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/event/eventlist.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/sixBoxLayout.xhtml">

    <ui:define name="center">
        <h:form>
            <p:dataTable value="#{manageEventBean.allEvents}" var="eventProxy" rows="6"
                         styleClass="create-game-data-table" paginator="true" paginatorPosition="bottom">
                <p:column headerText="Date" filterBy="#{eventProxy.dateFormatted}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.dateFormatted}"/>
                </p:column>
                <p:column headerText="Name" filterBy="#{eventProxy.event.name}" filterMatchMode="contains"
                          filterStyle="width: 70px">
                    <h:outputText value="#{eventProxy.event.name}"/>
                </p:column>
                <p:column headerText="Private" filterBy="#{eventProxy.event.privateEvent}" filterMatchMode="contains"
                          filterStyle="width: 70px">
                    <h:outputText value="#{eventProxy.event.privateEvent}"/>
                </p:column>
                <p:column headerText="Session" filterBy="#{eventProxy.sessionDescription}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.sessionDescription}"/>
                </p:column>
                <p:column headerText="Status" filterBy="#{eventProxy.statusDescription}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.statusDescription}"/>
                </p:column>
                <p:column headerText="Author" filterBy="#{eventProxy.authorDescription}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.authorDescription}"/>
                </p:column>
                <p:column headerText="Joined" filterBy="#{eventProxy.event.playersJoined}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.event.playersJoined}"/>
                </p:column>
                <p:column headerText="Max" filterBy="#{eventProxy.event.maxPlayerCount}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.event.maxPlayerCount}"/>
                </p:column>
                <p:column headerText="Location" filterBy="#{eventProxy.event.map.name}" filterMatchMode="contains"
                          filterStyle="width: 80px">
                    <h:outputText value="#{eventProxy.event.map.name}"/>
                </p:column>
                <p:column>
                    <p:commandButton value="EDIT"
                                    action="#{manageEventBean.edit(eventProxy)}"
                                    immediate="true"/>
                </p:column>
            </p:dataTable>
            <p:commandButton value="Back" action="../index.jsf?faces-redirect=true" immediate="true"/>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/admin/event/eventlistDisplayAlternateId.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html" 
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="/templates/sixBoxLayout.xhtml">

    <ui:define name="center">
        <h:form>
            <p:dataTable value="#{manageEventBean.allEvents}" var="eventProxy" rows="8"
                         styleClass="create-game-data-table" paginator="true" paginatorPosition="bottom">
                <p:column headerText="Date" filterBy="#{eventProxy.dateFormatted}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.dateFormatted}"/>
                </p:column>

                <p:column headerText="Name" filterBy="#{eventProxy.event.name}" filterMatchMode="contains"
                          filterStyle="width: 70px">
                    <p:commandLink value="#{eventProxy.event.name}"
                                   action="#{eventSelectionBean.setSelectedEvent(eventProxy)}"
                                   oncomplete="eventSignUpAdminDetailsWidgetVar.show()"
                                   update=":eventSignUpAdminDetailsForm:eventSignUpAdminDetailsDialog"
                                   rendered="#{eventProxy.event.playersJoined > 0}"/>

                    <h:outputText value="#{eventProxy.event.name}" rendered="#{eventProxy.event.playersJoined == 0}"/>

                </p:column>

                <p:column headerText="Session" filterBy="#{eventProxy.sessionDescription}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.sessionDescription}"/>
                </p:column>
                <p:column headerText="Joined" filterBy="#{eventProxy.event.playersJoined}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.event.playersJoined}"/>
                </p:column>
                <p:column headerText="Max" filterBy="#{eventProxy.event.maxPlayerCount}" filterMatchMode="contains"
                          filterStyle="width: 40px">
                    <h:outputText value="#{eventProxy.event.maxPlayerCount}"/>
                </p:column>
                <p:column headerText="Location" filterBy="#{eventProxy.event.map.name}" filterMatchMode="contains"
                          filterStyle="width: 80px">
                    <h:outputText value="#{eventProxy.event.map.name}"/>
                </p:column>
                <p:column>
                    <p:commandButton value="ALTERNATE ID"
                                     action="#{manageEventBean.displayAlternateId(eventProxy)}"
                                     immediate="true"/>
                </p:column>
            </p:dataTable>
            <p:commandButton value="Back" action="../index.jsf?faces-redirect=true" immediate="true"/>
        </h:form>
    </ui:define>
</ui:composition>